Add a blog post for visualizing graphs with grafana
aseriousbiz/blog pull request #10
Opened 2021-07-01 17:28 UTC by shana

What the title says!

2021-07-01 21:12 UTC, shana commented
Package is published at https://ab.bot/packages/aseriousbiz/grafana but it's marked as unlisted right now. Remember to list it when this goes up!

2021-07-02 03:34 UTC, haacked requested changes
This is fantastic! Just some minor suggestions and questions.

Could you copy the code of the `grafana` skill to a `grafana.cs` file in https://github.com/aseriousbiz/abbot-skills/tree/main/skills. And mention if anyone has issues or suggested improvements to the skill to submit it to that repository? I'll manually integrate changes as they come in (if they come in).

2021-07-02 03:34 UTC, haacked commented on _posts/2021/2021-07-01-graphs-in-chat.markdown
> +An image is worth a thousand words, which is why Abbot can now help you visualize your graphs on chat with the [grafana](https://ab.bot/packages/aseriousbiz/grafana) skill!
```suggestion
An image is worth a thousand words, which is why [Abbot](https://ab.bot/) can now help you visualize your graphs in chat with the [grafana](https://ab.bot/packages/aseriousbiz/grafana) skill!
```

2021-07-02 03:34 UTC, haacked commented on _posts/2021/2021-07-01-graphs-in-chat.markdown
> +Start by generating a Grafana API key on your Grafana host, usually found at https://your-grafana-host/org/apikeys. Then, visit [https://ab.bot/skills/grafana](https://ab.bot/skills/grafana) and clic
I think it looks good as code to indicate they should change it.

```suggestion
Start by generating a Grafana API key on your Grafana host, usually found at `https://your-grafana-host/org/apikeys`. Then, visit [https://ab.bot/skills/grafana](https://ab.bot/skills/grafana) and click "Manage skill secrets" to add a secret named ___GrafanaKey___, with the key you created.
```

2021-07-02 03:34 UTC, haacked commented on _posts/2021/2021-07-01-graphs-in-chat.markdown
> +This generates a graph of the `logins` panel in the `Home` dashboard with a time window of 2 days to 1 day from now.
I'm having trouble parsing what this time window means. Does it mean a time window of 2 days ending 1 day ago? Or a time window starting 2 days ago and ending 1 day ago?

2021-07-02 03:34 UTC, haacked commented on _posts/2021/2021-07-01-graphs-in-chat.markdown
> +A more complex query generated a templated Grafana graph with a time window of 24 hours, customized with several variables.
Is this sentence connected to the previous command?

```suggestion
The more complex query above generates a templated Grafana graph with a time window of 24 hours, customized with several variables.
```

2021-07-02 03:34 UTC, haacked commented on _posts/2021/2021-07-01-graphs-in-chat.markdown
> +Any parameter that Grafana supports in a query can be passed to the skill as key=value pairs, like timezone specifications or custom graph sizes:
```suggestion
Any parameter that Grafana supports in a query can be passed to the skill as `key=value` pairs, like timezone specifications or custom graph sizes:
```

2021-07-02 17:10 UTC, shana commented on _posts/2021/2021-07-01-graphs-in-chat.markdown
> +An image is worth a thousand words, which is why Abbot can now help you visualize your graphs on chat with the [grafana](https://ab.bot/packages/aseriousbiz/grafana) skill!
Oh yes, good point, was going to do that and forgot! :+1:

2021-07-02 17:11 UTC, shana commented on _posts/2021/2021-07-01-graphs-in-chat.markdown
> +This generates a graph of the `logins` panel in the `Home` dashboard with a time window of 2 days to 1 day from now.
Starting 2 days ago and ending 1 day ago. I'll rephrase!

2021-07-02 17:41 UTC, shana commented
> This is fantastic! Just some minor suggestions and questions.
> 
> Could you copy the code of the `grafana` skill to a `grafana.cs` file in https://github.com/aseriousbiz/abbot-skills/tree/main/skills. And mention if anyone has issues or suggested improvements to the skill to submit it to that repository? I'll manually integrate changes as they come in (if they come in).

Updated the blog post with a link to the skill in the skills repo :+1:

2021-07-02 17:46 UTC, merged