Fix donokuda hire post typos
aseriousbiz/blog pull request #15
Opened 2021-09-14 12:42 UTC by joshaber

@niik and I noticed a few typos so we went ahead and took care of them for you!

2021-09-14 14:38 UTC, pmn requested changes
@joshaber needed to make a few small changes for correctness. Either you or @niik are welcome to merge once you get here. Welcome aboard!

2021-09-14 14:38 UTC, pmn commented on _posts/2021/2021-09-13-don-okuda-is-an-abboteer.md
> +We’re excited to share that @niik and @joshaber have put Don back in the dryer and Don will be delivered back to GitHub ASAP.
```suggestion
We’re excited to share that @niik and @joshaber have also joined A Serious Business to help Don get out of the dryer and also because they miss working with @haacked, @shana, and @pmn, and they love working on bots.
```

2021-09-14 14:38 UTC, pmn commented on _posts/2021/2021-09-13-don-okuda-is-an-abboteer.md
> +![Mad Don](https://user-images.githubusercontent.com/13760/133258348-41e83378-fb4d-4e3c-9ec3-4167a25b0522.png)
😹 
<img width="1034" alt="and now it's in Abbot" src="https://user-images.githubusercontent.com/279389/133277691-ee7b1363-7950-4307-8d55-04cb57ce38ee.png">

2021-09-14 14:38 UTC, pmn commented on _posts/2021/2021-09-13-don-okuda-is-an-abboteer.md
> +We all worked with Don at GitHub on GitHub Desktop and can’t wait for him to go back to working on it!
```suggestion
We all worked with Don at GitHub on GitHub Desktop and can’t wait for Josh and Markus to work with us too!
```

2021-09-14 14:38 UTC, pmn commented on _posts/2021/2021-09-13-don-okuda-is-an-abboteer.md
> +Don insists he’s an actual human, so please join us in welcoming him back to GitHub!
```suggestion
Don insists he’s an actual human, so please join us in welcoming him, Markus, and Josh to A Serious Business!
```

2021-09-14 14:40 UTC, shana commented on _posts/2021/2021-09-13-don-okuda-is-an-abboteer.md
> +When he’s not making great products, Don makes music and enjoys pineapple on his pizza.
+1 this line change 🚀 :shipit:

2021-09-14 15:14 UTC, haacked commented
![](https://media.giphy.com/media/3o7aTpVyQCkQKfekVy/giphy.gif?cid=ecf05e47fuyt831p0vv9bwj47ojysoy7lctte7rstx8kzvbm&rid=giphy.gif&ct=g)

2021-09-14 16:27 UTC, donokuda commented
💯changes! 😂 

Can we also get some tests in here to make sure this doesn't regress?? 🙏

2021-11-02 21:20 UTC, closed without merging

2021-11-02 21:22 UTC, joshaber commented
![RUDE](https://user-images.githubusercontent.com/13760/139953603-3247708c-7308-4e18-bac3-c1a58ebece9b.gif)